### ISSUE TITLE
第3周：0111-0115

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.requirement#89]
### UI

- [x] #62 笔记功能
- [x] #81 挑战活动调整

### API

- [x] #62 笔记功能
- [x] #84 优化 Library API
- [x] #97 依据订阅推送，实时更新有效期
- [x] #96 华为支付

### IOS

- [x] #87 书籍页点击播放或阅读，恢复上次学习的章节
- [x] #86 切换章节时，保持播放与阅读一致
- [x] #60 文章内容反馈功能
- [x] #62 笔记功能

### Android

- [x] #46 Me 页面调整（二级类目学习情况）
- [x] #78 上报 `7天试用转化成功` 事件
- [x] #63 手动 mark
